apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-prometheus-demo
spec:
  selector:
    matchLabels:
      run: django-demo-prometheus
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"

      labels:
        run: django-demo-prometheus
    spec:
      containers:
      - name: django-demo-prometheus
        image: iimnd/django-prometheus:1.0.2
        env:
        - name: VERSION
          value: 2.0.1
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: django-prometheus-demo-svc
spec:
  type: ClusterIP
  selector:
    run: django-demo-prometheus
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
